# Generated by Django 4.0.4 on 2022-07-11 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=10)),
                ('first_name', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('timetable', models.ImageField(blank=True, null=True, upload_to='calendar/')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='')),
                ('major', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필(들)',
            },
        ),
    ]
