# Generated by Django 4.0.4 on 2022-07-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usericon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
