# Generated by Django 4.0.4 on 2022-07-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
