# Generated by Django 4.0.4 on 2022-06-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mbti',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
