# Generated by Django 4.0.4 on 2022-07-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
