# Generated by Django 4.0.4 on 2022-07-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False)),
                ('startday', models.DateField(verbose_name='프로젝트 시작일')),
                ('endday', models.DateField(verbose_name='프로젝트 마감일')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
            },
        ),
    ]
