# Generated by Django 3.2.4 on 2022-07-10 02:37

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=colorfield.fields.ColorField(default='#50cfbc', image_field=None, max_length=18, samples=[('#50cfbc', '1'), ('#fe7782', '2'), ('#45bfff', '3'), ('#ffbc54', '4'), ('#735bf2', '5')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
