# Generated by Django 4.0.4 on 2022-07-10 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(related_name='followers', through='addproject.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
