# Generated by Django 4.0.4 on 2022-07-06 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '프로젝트', 'verbose_name_plural': '프로젝트들'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='otheruser',
            new_name='usericon',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='project',
            name='endday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='project',
            name='startday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
