# Generated by Django 4.0.4 on 2022-07-06 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='프로젝트 마감일'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='프로젝트 시작일'),
        ),
    ]
