# Generated by Django 3.2.4 on 2022-07-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0002_auto_20220710_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startday',
            field=models.DateField(),
        ),
    ]
