# Generated by Django 4.0.4 on 2022-07-06 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0003_alter_project_endday_alter_project_startday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='usericon',
        ),
    ]
