# Generated by Django 4.0.4 on 2022-07-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='dday',
            field=models.IntegerField(default=0),
        ),
    ]
