# Generated by Django 4.0.4 on 2022-07-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='mateapp.calendar'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
