# Generated by Django 4.0.4 on 2022-07-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='datetime',
            field=models.DateField(),
        ),
    ]
