# Generated by Django 4.0.4 on 2022-07-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='startday',
            field=models.DateField(null=True),
        ),
    ]
