# Generated by Django 4.0.4 on 2022-07-03 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': '캘린더', 'verbose_name_plural': '캘린더(들)'},
        ),
        migrations.RenameField(
            model_name='calendar',
            old_name='pub_date',
            new_name='datetime',
        ),
    ]
