# Generated by Django 4.0.4 on 2022-07-09 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0001_initial'),
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addproject.project'),
        ),
    ]
