# Generated by Django 4.0.4 on 2022-07-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
