# Generated by Django 4.0.4 on 2022-07-06 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mateapp.todotitle'),
        ),
    ]
