# Generated by Django 4.0.4 on 2022-07-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0002_todolist_todolist_files_todolist_images_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist_images',
            name='todo',
        ),
        migrations.DeleteModel(
            name='TodoList_files',
        ),
        migrations.DeleteModel(
            name='TodoList_images',
        ),
    ]
