# Generated by Django 4.0.4 on 2022-07-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0002_alter_calendar_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='startday',
        ),
    ]
