# Generated by Django 4.0.4 on 2022-07-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0002_todocomment_todotitle_delete_todo_todocomment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotitle',
            old_name='title',
            new_name='content',
        ),
    ]
