# Generated by Django 4.0.4 on 2022-07-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0002_calendar_dday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='dday',
        ),
    ]
