# Generated by Django 4.0.4 on 2022-07-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0003_remove_todolist_images_todo_delete_todolist_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
