# Generated by Django 4.0.4 on 2022-07-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0003_remove_calendar_dday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todocomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todocomment',
            name='update_at',
        ),
    ]
