# Generated by Django 4.0.4 on 2022-07-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0003_rename_datetime_calendar_endday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='endday',
        ),
    ]
