# Generated by Django 4.0.4 on 2022-07-09 05:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0003_remove_calendar_startday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='color',
            field=colorfield.fields.ColorField(default='#50cfbc', image_field=None, max_length=18, samples=[('#50cfbc', '1'), ('#fe7782', '2'), ('#45bfff', '3'), ('#ffbc54', '4'), ('#735bf2', '5')]),
        ),
    ]
