# Generated by Django 4.0.4 on 2022-07-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0003_rename_title_todotitle_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotitle',
            old_name='content',
            new_name='title',
        ),
    ]
