# Generated by Django 4.0.4 on 2022-07-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0004_todo_delete_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='classname',
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
