# Generated by Django 4.0.4 on 2022-07-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0004_rename_content_todotitle_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todocomment',
            name='writer',
        ),
    ]
