# Generated by Django 4.0.4 on 2022-07-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0004_remove_post_writer_delete_comment_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
