# Generated by Django 4.0.4 on 2022-07-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0004_remove_calendar_endday'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='endday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='startday',
            field=models.DateField(null=True),
        ),
    ]
