# Generated by Django 4.0.4 on 2022-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0004_remove_todocomment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocomment',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
