# Generated by Django 4.0.4 on 2022-07-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0005_calendar_endday_calendar_startday'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
