# Generated by Django 4.0.4 on 2022-07-07 20:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mateapp', '0006_calendar_endtime_calendar_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#50cfbc', '1'), ('#fe7782', '2'), ('#45bfff', '3'), ('#ffbc54', '4'), ('#735bf2', '5')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
